import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';

const html=readFileSync(new URL('../index.html',import.meta.url),'utf8');
const main=readFileSync(new URL('../src/main.js',import.meta.url),'utf8');
const styles=readFileSync(new URL('../src/styles.css',import.meta.url),'utf8');
const activity=readFileSync(new URL('../android-remote/app/src/main/java/tw/club7b/scoreremote/MainActivity.java',import.meta.url),'utf8');
const service=readFileSync(new URL('../android-remote/app/src/main/java/tw/club7b/scoreremote/RemoteKeyAccessibilityService.java',import.meta.url),'utf8');
const controller=readFileSync(new URL('../android-remote/app/src/main/java/tw/club7b/scoreremote/BackgroundScoreController.java',import.meta.url),'utf8');
const interpreter=readFileSync(new URL('../android-remote/app/src/main/java/tw/club7b/scoreremote/VolumeKeyInterpreter.java',import.meta.url),'utf8');
const yuntengGestures=readFileSync(new URL('../android-remote/app/src/main/java/tw/club7b/scoreremote/YuntengGestureInterpreter.java',import.meta.url),'utf8');
const cameraActivity=readFileSync(new URL('../android-remote/app/src/main/java/tw/club7b/scoreremote/LoopCameraActivity.java',import.meta.url),'utf8');

test('shows one-shuttle controls in scoring and next-match result views plus dashboard summary',()=>{
  for(const id of ['homeShuttleSummary','scoreUseShuttle','resultUseShuttle','resultReturnShuttle'])assert.match(html,new RegExp(`id="${id}"`));
  assert.match(html,/id="resultUseShuttle"[^>]*>−1<\/button>/);
  assert.match(html,/id="resultReturnShuttle"[^>]*>\+1<\/button>/);
  assert.doesNotMatch(html,/id="result(?:Use|Return)Shuttle"[^>]*>[^<]*🏸/);
  assert.match(main,/function useOneShuttle\(/);
  assert.match(main,/id="homeShuttleManagerBtn"[^>]*>球桶管理<\/button>/);
  assert.match(main,/\$\('homeShuttleManagerBtn'\)\?\.addEventListener\('click',openShuttleTubeManager\)/);
  assert.match(main,/adjustSessionShuttleUsage\(row,-1,shuttleUsageSessionKey\(\)\)/);
  assert.match(main,/adjustSessionShuttleUsage\(row,1,shuttleUsageSessionKey\(\)\)/);
  assert.match(main,/adjustSessionShuttleUsage\(tube,delta,shuttleUsageSessionKey\(\)\)/);
  assert.match(main,/if\(\(roomWriteScheduled\|\|pendingRoomWrites>0\)&&!snapshotHasPendingWrites\)\{updateSyncBadge\(\);return\}/);
  assert.match(main,/function returnOneShuttle\(/);
  assert.match(main,/data-shuttle-delta="-1"[^>]*>−1<\/button>/);
  assert.match(main,/data-shuttle-delta="1"[^\n]*?>\+1<\/button>/);
  assert.match(main,/已加回 1 顆球｜剩餘/);
  assert.match(main,/showScoreRemoteIndicator\(`已使用 1 顆球｜剩餘 \$\{updated\.remainingShuttles\} 顆`,\{duration:2000,icon:'🏸'\}\)/);
  assert.match(main,/resultModal&&!resultModal\.classList\.contains\('hidden'\)\?resultModal:\(currentFullscreenElement\(\)\|\|\$\('scoreView'\)\)/);
  assert.match(main,/overlayHost\.append\(indicator\)/);
  assert.match(styles,/\.score-remote-indicator\{[^}]*z-index:1000/);
  assert.doesNotMatch(main,/if\(source==='remote'\)showScoreRemoteIndicator\(`已使用 1 顆/);
  assert.match(main,/class="home-shuttle-fee-amount">\$\{players\?`每人 \$\{formatMoney\(share\)\} 元`/);
  assert.match(main,/ensureShuttleCostNotice/);
  assert.match(main,/sessionCombinedCosts\(e\)/);
  assert.match(main,/next-event-payment">場租及球費 <strong class="next-event-fee-amount">\$\{formatMoney\(perPersonFee\)\} 元/);
  assert.match(styles,/\.home-shuttle-fee-amount\{[^}]*font-size:1\.16rem/);
  assert.match(styles,/\.next-event-fee-amount\{[^}]*font-size:1\.18em/);
  assert.doesNotMatch(html,/勝方兩人保留，候場隊首兩人上場/);
  assert.doesNotMatch(html,/id="priorityText"/);
  assert.doesNotMatch(main,/\$\('priorityText'\)/);
  assert.match(styles,/#resultModal \.next-team/);
});

test('routes YUNTENG keys directly without multi-press delay',()=>{
  for(const source of [activity,service]){
    assert.match(source,/Action previousAction = \w+Keys\.onMissingKeyUp\(keyCode\);[\s\S]*?handleResolved\w+Action\(previousAction, keyCode, event\.getEventTime\(\)\);/);
    assert.match(source,/SHUTTLE_PRESS_COOLDOWN_MS = 2000L/);
    assert.match(source,/Action\.USE_SHUTTLE[\s\S]*?Action\.RETURN_SHUTTLE/);
    assert.doesNotMatch(source,/pendingShortPressCount|SHUTTLE_SEQUENCE_MS/);
    assert.match(source,/action == VolumeKeyInterpreter\.Action\.UNDO/);
  }
  assert.match(interpreter,/KEYCODE_VOLUME_UP:[\s\S]*?TEAM_A_PLUS/);
  assert.match(interpreter,/KEYCODE_VOLUME_DOWN:[\s\S]*?TEAM_B_PLUS/);
  assert.match(interpreter,/KEYCODE_CAMERA:[\s\S]*?USE_SHUTTLE/);
  assert.match(interpreter,/longPressAction[\s\S]*?KEYCODE_VOLUME_UP[\s\S]*?Action\.UNDO[\s\S]*?Action\.RETURN_SHUTTLE/);
  assert.match(activity,/scoreController\(\)\.useOneShuttle/);
  assert.match(activity,/scoreController\(\)\.returnOneShuttle/);
  assert.match(service,/useOneShuttle/);
  assert.match(service,/returnOneShuttle/);
  assert.match(activity,/sendRemoteOfficialStartCommand\(\).*backgroundScoreController\.startOfficialMatch/s);
  assert.match(controller,/startOfficialMatch\(FullscreenCallback callback\).*transaction\.get\(liveScore\).*command\.put\("matchId", String\.valueOf\(matchId\)\).*updates\.put\("officialStartCommand", command\).*transaction\.set\(remoteControl/s);
  assert.match(controller,/sendShuttleCommand\("useShuttle"/);
  assert.match(controller,/sendShuttleCommand\("returnShuttle"/);
  assert.match(controller,/sendShuttleCommand[\s\S]*?if\(!session\.isAuthorized\(\)\)[\s\S]*?transaction\.get\(liveScore\)[\s\S]*?Boolean\.TRUE\.equals\(match\.get\("active"\)\)/);
  assert.doesNotMatch(controller,/sendShuttleCommand[\s\S]*?if\(!session\.isReady\(\)\)/);
  assert.match(controller,/startOfficialMatch[\s\S]*?if \(!session\.isAuthorized\(\)\)[\s\S]*?transaction\.get\(liveScore\)/);
  assert.match(controller,/private synchronized void processNext\(\).*transaction\.get\(liveScore\).*command\.put\("matchId", String\.valueOf\(matchId\)\).*transaction\.set\(remoteControl/s);
  assert.match(main,/\['teamAPlus','teamBPlus','undo','useShuttle','returnShuttle'\]/);
  assert.match(main,/if\(!scoreVisible&&!resultVisible\)\{\s*if\(courtVisible&&\['teamAPlus','teamBPlus'\]\.includes\(action\)\)/);
  assert.match(main,/if\(action==='useShuttle'\)return useOneShuttle/);
  assert.match(main,/if\(action==='returnShuttle'\)return returnOneShuttle/);
  assert.match(main,/if\(resultVisible\)\{if\(action==='undo'\)performScoreRemoteAction\('undo',\{announce:false\}\);else startNext\(\);return true\}/);
});

test('converts YUNTENG zoom gestures into score keys in remote and recording screens',()=>{
  assert.match(yuntengGestures,/TEAM_SPLIT = 0\.45f/);
  assert.match(yuntengGestures,/TEAM_A_PLUS[\s\S]*?TEAM_B_PLUS/);
  assert.match(yuntengGestures,/horizontalGesture[\s\S]*?newX[\s\S]*?newY/);
  assert.match(yuntengGestures,/HORIZONTAL_TEAM_SPLIT = 0\.865f/);
  assert.match(yuntengGestures,/rangeMax < 1500f[\s\S]*?HORIZONTAL_TEAM_SPLIT/);
  assert.match(yuntengGestures,/ACTION_POINTER_DOWN[\s\S]*?return classifyAxes/);
  assert.match(yuntengGestures,/LONG_PRESS_MS = 2000L/);
  assert.doesNotMatch(yuntengGestures,/LONG_GESTURE_TRAVEL/);
  assert.match(yuntengGestures,/POST_LONG_PRESS_IGNORE_MS = 500L/);
  assert.doesNotMatch(yuntengGestures,/suppressUntilRelease/);
  assert.match(yuntengGestures,/onShortPressTimeout\(\)/);
  assert.match(activity,/dispatchTouchEvent\(MotionEvent event\)[\s\S]*?sendYuntengScoreAction\(action\)/);
  assert.match(activity,/sendYuntengScoreAction[\s\S]*?scoreController\(\)\.submit\(action/);
  assert.match(activity,/SHORT_CONFIRM_MS[\s\S]*?LONG_PRESS_MS/);
  assert.match(cameraActivity,/SHORT_CONFIRM_MS[\s\S]*?LONG_PRESS_MS/);
  assert.match(yuntengGestures,/onLongPressTimeout\(\)[\s\S]*?Action\.UNDO/);
  assert.match(activity,/CAMERA_DOUBLE_PRESS_MS = 800L[\s\S]*?handleCameraShortPress/);
  assert.match(service,/CAMERA_DOUBLE_PRESS_MS = 800L[\s\S]*?handleCameraShortPress/);
  assert.match(activity,/pendingCameraSinglePress != null[\s\S]*?sendRemoteUseShuttleCommand\(\)[\s\S]*?pendingCameraSinglePress = \(\) -> \{[\s\S]*?sendRemoteAction\(VolumeKeyInterpreter\.Action\.UNDO\)/);
  assert.match(service,/pendingCameraSinglePress != null[\s\S]*?sendBackgroundUseShuttle\(\)[\s\S]*?pendingCameraSinglePress = \(\) -> \{[\s\S]*?sendBackgroundAction\(VolumeKeyInterpreter\.Action\.UNDO\)/);
  assert.match(yuntengGestures,/YUNTENG[\s\S]*?KEYCODE_CAMERA/);
  assert.match(cameraActivity,/dispatchTouchEvent\(MotionEvent event\)[\s\S]*?sendYuntengScore\(action\)/);
  assert.match(cameraActivity,/remoteScoreController\.submit\(action/);
});
