import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';

const html=readFileSync(new URL('../index.html',import.meta.url),'utf8');
const main=readFileSync(new URL('../src/main.js',import.meta.url),'utf8');
const styles=readFileSync(new URL('../src/styles.css',import.meta.url),'utf8');
const activity=readFileSync(new URL('../android-remote/app/src/main/java/tw/club7b/scoreremote/MainActivity.java',import.meta.url),'utf8');
const service=readFileSync(new URL('../android-remote/app/src/main/java/tw/club7b/scoreremote/RemoteKeyAccessibilityService.java',import.meta.url),'utf8');
const controller=readFileSync(new URL('../android-remote/app/src/main/java/tw/club7b/scoreremote/BackgroundScoreController.java',import.meta.url),'utf8');
const interpreter=readFileSync(new URL('../android-remote/app/src/main/java/tw/club7b/scoreremote/VolumeKeyInterpreter.java',import.meta.url),'utf8');
const yuntengGestures=readFileSync(new URL('../android-remote/app/src/main/java/tw/club7b/scoreremote/YuntengGestureInterpreter.java',import.meta.url),'utf8');
const cameraActivity=readFileSync(new URL('../android-remote/app/src/main/java/tw/club7b/scoreremote/LoopCameraActivity.java',import.meta.url),'utf8');

test('shows one-shuttle controls in scoring and next-match result views plus dashboard summary',()=>{
  for(const id of ['homeShuttleSummary','scoreUseShuttle','resultUseShuttle','resultReturnShuttle'])assert.match(html,new RegExp(`id="${id}"`));
  assert.match(html,/id="resultUseShuttle"[^>]*>−1<\/button>/);
  assert.match(html,/id="resultReturnShuttle"[^>]*>\+1<\/button>/);
  assert.doesNotMatch(html,/id="result(?:Use|Return)Shuttle"[^>]*>[^<]*🏸/);
  assert.match(main,/function useOneShuttle\(/);
  assert.match(main,/id="homeShuttleManagerBtn"[^>]*>球桶管理<\/button>/);
  assert.match(main,/\$\('homeShuttleManagerBtn'\)\?\.addEventListener\('click',openShuttleTubeManager\)/);
  assert.match(main,/adjustSessionShuttleUsage\(row,-1,shuttleUsageSessionKey\(\)\)/);
  assert.match(main,/adjustSessionShuttleUsage\(row,1,shuttleUsageSessionKey\(\)\)/);
  assert.match(main,/adjustSessionShuttleUsage\(tube,delta,shuttleUsageSessionKey\(\)\)/);
  assert.match(main,/if\(\(roomWriteScheduled\|\|pendingRoomWrites>0\)&&!snapshotHasPendingWrites\)\{updateSyncBadge\(\);return\}/);
  assert.match(main,/function returnOneShuttle\(/);
  assert.match(main,/data-shuttle-delta="-1"[^>]*>−1<\/button>/);
  assert.match(main,/data-shuttle-delta="1"[^\n]*?>\+1<\/button>/);
  assert.match(main,/已加回 1 顆球｜剩餘/);
  assert.match(main,/showScoreRemoteIndicator\(`已使用 1 顆球｜剩餘 \$\{updated\.remainingShuttles\} 顆`,\{duration:2000,icon:'🏸'\}\)/);
  assert.match(main,/resultModal&&!resultModal\.classList\.contains\('hidden'\)\?resultModal:\(currentFullscreenElement\(\)\|\|\$\('scoreView'\)\)/);
  assert.match(main,/overlayHost\.append\(indicator\)/);
  assert.match(styles,/\.score-remote-indicator\{[^}]*z-index:1000/);
  assert.doesNotMatch(main,/if\(source==='remote'\)showScoreRemoteIndicator\(`已使用 1 顆/);
  assert.match(main,/class="home-shuttle-fee-amount">\$\{players\?`每人 \$\{formatMoney\(share\)\} 元`/);
  assert.match(main,/ensureShuttleCostNotice/);
  assert.match(main,/sessionCombinedCosts\(e\)/);
  assert.match(main,/next-event-payment">場租及球費 <strong class="next-event-fee-amount">\$\{formatMoney\(perPersonFee\)\} 元/);
  assert.match(styles,/\.home-shuttle-fee-amount\{[^}]*font-size:1\.16rem/);
  assert.match(styles,/\.next-event-fee-amount\{[^}]*font-size:1\.18em/);
  assert.doesNotMatch(html,/勝方兩人保留，候場隊首兩人上場/);
  assert.doesNotMatch(html,/id="priorityText"/);
  assert.doesNotMatch(main,/\$\('priorityText'\)/);
  assert.match(styles,/#resultModal \.next-team/);
});

test('routes YUNTENG keys directly without multi-press delay',()=>{
  for(const source of [activity,service]){
    assert.match(source,/Action previousAction = \w+Keys\.onMissingKeyUp\(keyCode\);[\s\S]*?handleResolved\w+Action\(previousAction, keyCode, event\.getEventTime\(\)\);/);
    assert.match(source,/SHUTTLE_PRESS_COOLDOWN_MS = 2000L/);
    assert.match(source,/Action\.USE_SHUTTLE[\s\S]*?Action\.RETURN_SHUTTLE/);
    assert.doesNotMatch(source,/pendingShortPressCount|SHUTTLE_SEQUENCE_MS/);
    assert.match(source,/action == VolumeKeyInterpreter\.Action\.UNDO/);
  }
  assert.match(interpreter,/KEYCODE_VOLUME_UP:[\s\S]*?TEAM_A_PLUS/);
  assert.match(interpreter,/KEYCODE_VOLUME_DOWN:[\s\S]*?TEAM_B_PLUS/);
  assert.match(interpreter,/KEYCODE_CAMERA:[\s\S]*?USE_SHUTTLE/);
  assert.match(interpreter,/longPressAction[\s\S]*?KEYCODE_VOLUME_UP[\s\S]*?Action\.UNDO[\s\S]*?Action\.RETURN_SHUTTLE/);
  assert.match(activity,/scoreController\(\)\.useOneShuttle/);
  assert.match(activity,/scoreController\(\)\.returnOneShuttle/);
  assert.match(service,/useOneShuttle/);
  assert.match(service,/returnOneShuttle/);
  assert.match(activity,/sendRemoteOfficialStartCommand\(\).*backgroundScoreController\.startOfficialMatch/s);
  assert.match(controller,/startOfficialMatch\(FullscreenCallback callback\).*transaction\.get\(liveScore\).*transaction\.set\(remoteControl, officialStartUpdates\(String\.valueOf\(matchId\), clientCreatedAt\)/s);
  assert.match(controller,/officialStartUpdates\(String matchId, long clientCreatedAt\)[\s\S]*?updates\.put\("officialStartCommand", command\)/);
  assert.match(controller,/sendShuttleCommand\("useShuttle"/);
  assert.match(controller,/sendShuttleCommand\("returnShuttle"/);
  assert.match(controller,/sendShuttleCommand[\s\S]*?if\(!session\.isAuthorized\(\)\)[\s\S]*?transaction\.get\(liveScore\)[\s\S]*?Boolean\.TRUE\.equals\(match\.get\("active"\)\)/);
  assert.doesNotMatch(controller,/sendShuttleCommand[\s\S]*?if\(!session\.isReady\(\)\)/);
  assert.match(controller,/startOfficialMatch[\s\S]*?if \(!session\.isAuthorized\(\)\)[\s\S]*?transaction\.get\(liveScore\)/);
  assert.match(controller,/private void sendAction\(Request request\).*knownMatchId\(\).*deliverAction\(remoteControl, request, cachedMatchId\)/s);
  assert.match(controller,/remoteControl\.getParent\(\)\.document\("score-" \+ id\)\.set\(command\)/);
  assert.match(main,/\['teamAPlus','teamBPlus','undo','useShuttle','returnShuttle'\]/);
  assert.match(main,/if\(!scoreVisible&&!resultVisible\)\{\s*if\(courtVisible&&\['teamAPlus','teamBPlus'\]\.includes\(action\)\)/);
  assert.match(main,/if\(action==='useShuttle'\)return useOneShuttle/);
  assert.match(main,/if\(action==='returnShuttle'\)return returnOneShuttle/);
  assert.match(main,/if\(resultVisible\)\{if\(action==='undo'\)performScoreRemoteAction\('undo',\{announce:false\}\);else startNext\(\);return true\}/);
});

test('converts YUNTENG zoom gestures into score keys in remote and recording screens',()=>{
  assert.match(yuntengGestures,/TEAM_SPLIT = 0\.45f/);
  assert.match(yuntengGestures,/TEAM_A_PLUS[\s\S]*?TEAM_B_PLUS/);
  assert.match(yuntengGestures,/horizontalGesture[\s\S]*?Math\.max\(x0, x1\)[\s\S]*?Math\.max\(y0, y1\)/);
  assert.match(yuntengGestures,/HORIZONTAL_TEAM_SPLIT = 0\.865f/);
  assert.match(yuntengGestures,/rangeMax < 1500f[\s\S]*?HORIZONTAL_TEAM_SPLIT/);
  assert.match(yuntengGestures,/ACTION_POINTER_DOWN[\s\S]*?pendingAxisStart/);
  assert.match(yuntengGestures,/GESTURE_SETTLE_MS = 40L/);
  assert.match(yuntengGestures,/ACTION_MOVE[\s\S]*?gestureAction = candidate/);
  assert.match(yuntengGestures,/ACTION_POINTER_UP[\s\S]*?ACTION_UP[\s\S]*?pendingAction = gestureAction/);
  assert.match(yuntengGestures,/delta > 0f[\s\S]*?TEAM_A_PLUS[\s\S]*?TEAM_B_PLUS/);
  assert.match(yuntengGestures,/Math\.max\(x0, x1\)[\s\S]*?Math\.max\(y0, y1\)/);
  assert.match(yuntengGestures,/onSettledPress\(\)/);
  assert.match(activity,/dispatchTouchEvent\(MotionEvent event\)[\s\S]*?sendYuntengScoreAction\(action\)/);
  assert.match(activity,/sendYuntengScoreAction[\s\S]*?scoreController\(\)\.submit\(action/);
  assert.match(activity,/postDelayed\(pendingYuntengPress, YuntengGestureInterpreter\.GESTURE_SETTLE_MS\)/);
  assert.match(cameraActivity,/postDelayed\(pendingYuntengPress, YuntengGestureInterpreter\.GESTURE_SETTLE_MS\)/);
  assert.match(activity,/if \(pendingYuntengPress != null\) keyHandler\.removeCallbacks\(pendingYuntengPress\)[\s\S]*?postDelayed\(pendingYuntengPress/);
  assert.match(cameraActivity,/if \(pendingYuntengPress != null\) handler\.removeCallbacks\(pendingYuntengPress\)[\s\S]*?postDelayed\(pendingYuntengPress/);
  assert.doesNotMatch(yuntengGestures,/700L|2000L|Action\.UNDO/);
  assert.doesNotMatch(activity,/CAMERA_DOUBLE_PRESS_MS|handleCameraShortPress|sendRemoteAction\(VolumeKeyInterpreter\.Action\.UNDO\)/);
  assert.doesNotMatch(service,/CAMERA_DOUBLE_PRESS_MS|handleCameraShortPress|sendBackgroundAction\(VolumeKeyInterpreter\.Action\.UNDO\)/);
  assert.doesNotMatch(yuntengGestures,/KEYCODE_VOLUME_UP && deviceName/);
  assert.match(cameraActivity,/dispatchTouchEvent\(MotionEvent event\)[\s\S]*?sendYuntengScore\(action\)/);
  assert.match(cameraActivity,/remoteScoreController\.submit\(action/);
});
