plugins { id 'com.android.application' }

android {
    namespace 'tw.club7b.app'
    compileSdk 36
    defaultConfig {
        applicationId 'tw.club7b.badminton'
        minSdk 26
        targetSdk 35
        versionCode 1
        versionName '1.0.0'
    }
}

dependencies { implementation 'androidx.activity:activity:1.12.2' }
